### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Graveyard9988** [kyochikuto/sing-box#1]
### Operating system

Android

### System version

1.8

### Installation type

Original sing-box Command Line

### Version

<details>

```console
# Replace this line with the output
```
</details>

### Description

درود 
ایا در کلاینت اصلی سینگ باکس امکان وارد گردن فرگمنت در فایل جیسن وجود دارد؟

در فورک زیر چطور؟https://github.com/maskedeken/sing-box

### Reproduction

.

### Logs

<details>

```console
# Replace this line with logs
```
</details>

**Comment by kyochikuto** [comment]
سلام

خیر PR من برای این مورد مورد قبول برنامه نویس اصلی واقع نشد و در هسته ی اصلی این امکان وجود نداره در حال حاضر فقط از وجود این ویژگی در فورک شخصی خودم و هیدیفای اطلاع دارم.

**Comment by kyochikuto** [comment]
> سپاس اگر ممکنه فورک خودتون رو با آخرین نسخه ۱.۸.۵ به روزرسانی کنین و طریقه استفاده از فرگمنت در فورک خودتون رو بنویسین
> 
> سپاس دوباره

بروزرسانی شد و فایل های اجرایی رو از قسمت [Releases](https://github.com/kyochikuto/sing-box/releases) دریافت کنید.

**Comment by kyochikuto** [comment]
> سپاس در مورد پارامتر های فرگمنت اگر ممکنه توضیح بدهید چرا که با هیدیفای و xray متفاوت است و یک مقدار ابهام ایجاد می کند

هیدیفای که از همین پیاده سازی استفاده می‌کنه اما معادل های xray به شرح زیر هستند:
```
length = size
interval = sleep
```

**Comment by kyochikuto** [comment]
از لطف شما متشکرم. به امید آزادی ایران. پیروز باشید.
